---
- name: Install KVM and dependancies
  hosts: nodes
  become: true
  #vars_prompt:
  #  - name: "ansible_user"
  #    prompt: "Enter the username for SSH"
  #    private: no
  #  - name: "ansible_password"
  #    prompt: "Enter the password for SSH"
  #    private: yes
  
  vars:
  #  ansible_python_interpreter: /usr/bin/python3.11
    packages:
      - qemu-system
      - libvirt-daemon-system
      - virtinst
      - libvirt-clients
      - dnsmasq-base
      - bridge-utils
      - firewalld
    services:
      - firewalld

  roles:
    #- depends
    # - network
    - kvm_config
  tasks:
